### ISSUE TITLE
Excellent work.

### ISSUE THREAD

**Issue by Patrick0169** [nioc/linky-collector#3]
Hello,

You really did a great job.
I put it in place without any problem and compared with data that I recovered from another application.
For me, the data is correct in Grafana.

Thank you very much for this excellent job.

Patrick

**Comment by nioc** [comment]
Thanks Patrick 😊
Unfortunately, this script does not work anymore since Enedis has changed authentication mechanism without providing public API…
I create issue #4 for following.

**Comment by Patrick0169** [comment]
Hi Nicolas,

Nothing has been working since Enedis has changed authentification.

Patrick
